name: tiki_sdk_native
description: Use TIKI's dart libs in native projects
version: 2.0.4
homepage: https://mytiki.com
documentation: https://mytiki.com/docs
repository: https://github.com/tiki/tiki_sdk_native
issue_tracker: https://github.com/tiki/tiki_sdk_native/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  tiki_idp: ^0.1.1
  tiki_trail: ^3.0.4
  sqlite3: ^1.9.3
  sqlite3_flutter_libs: ^0.5.13
  pointycastle: ^3.7.3

dev_dependencies:
  flutter_lints: ^2.0.1
  uuid: ^3.0.7
  mockito: ^5.4.2
  build_runner: ^2.4.6
  test: ^1.24.1

flutter:
  module:
    androidX: true
    androidPackage: com.mytiki.tiki_sdk_native
    iosBundleIdentifier: com.mytiki.tiki_sdk_native
